# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: playground.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'playground.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10playground.proto\x12\nplayground\"\x9c\x01\n\x1e\x43reatePolygonPlaygroundRequest\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x02\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x11\n\tstop_date\x18\x03 \x01(\t\x12\x0e\n\x06symbol\x18\x04 \x01(\t\x12\x1b\n\x13timespan_multiplier\x18\x05 \x01(\r\x12\x15\n\rtimespan_unit\x18\x06 \x01(\t\"&\n\x18\x43reatePlaygroundResponse\x12\n\n\x02id\x18\x01 \x01(\t2y\n\x11PlaygroundService\x12\x64\n\x10\x43reatePlayground\x12*.playground.CreatePolygonPlaygroundRequest\x1a$.playground.CreatePlaygroundResponseB\x0eZ\x0c./playgroundb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'playground_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014./playground'
  _globals['_CREATEPOLYGONPLAYGROUNDREQUEST']._serialized_start=33
  _globals['_CREATEPOLYGONPLAYGROUNDREQUEST']._serialized_end=189
  _globals['_CREATEPLAYGROUNDRESPONSE']._serialized_start=191
  _globals['_CREATEPLAYGROUNDRESPONSE']._serialized_end=229
  _globals['_PLAYGROUNDSERVICE']._serialized_start=231
  _globals['_PLAYGROUNDSERVICE']._serialized_end=352
# @@protoc_insertion_point(module_scope)
