name: trading
channels:
  - anaconda
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - exchange-calendars=4.8
  - h2=4.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - joblib=1.4.2
  - korean_lunar_calendar=0.3.1
  - libcxx=19.1.7
  - libffi=3.4.6
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblzma=5.6.4
  - libopenblas=0.3.29
  - libsqlite=3.49.1
  - libta-lib=0.4.0
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - loguru=0.7.2
  - ncurses=6.5
  - numpy=1.21.6
  - numpy-base=1.21.6
  - openssl=3.4.1
  - pandas=1.3.5
  - pandas-ta=0.3.14b
  - pandas_market_calendars=4.6.1
  - pip=25.0.1
  - polygon-api-client=1.12.8
  - pycparser=2.22
  - pyluach=2.2.0
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pytz=2025.1
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.3.0
  - scipy=1.11.4
  - setuptools=59.8.0
  - six=1.17.0
  - ta-lib=0.4.19
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - toolz=1.0.0
  - tzdata=2025a
  - urllib3=2.3.0
  - websockets=15.0
  - wheel=0.45.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - protobuf==5.29.3
      - structlog==25.1.0
      - twirp==0.0.7
      - typing-extensions==4.12.2
