name: trading
channels:
  - anaconda
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - loguru=0.7.2
  - numpy=1.21.6
  - numpy-base=1.21.6
  - pandas=1.3.5
  - pandas-ta=0.3.14b
  - pandas_market_calendars=4.6.1
  - pip=25.0.1
  - polygon-api-client=1.12.8
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pytz=2025.1
  - requests=2.32.3
  - scikit-learn=1.3.0
  - scipy=1.11.4
  - setuptools=59.8.0
  - six=1.17.0
  - ta-lib=0.4.19
  - pip:
      - protobuf==5.29.3
      - structlog==25.1.0
      - twirp==0.0.7
      - typing-extensions==4.12.2
