module.exports = {
  apps : [{
    name: 'optimizer-aapl',
    cmd: 'src/cmd/stats/trading_engine_optimizer.py',
    args: '',
    autorestart: false,
    watch: false,
    instances: 1,
    max_memory_restart: '1G',
    env: {
      BALANCE: '10000',
      SYMBOL: 'AAPL',
      TWIRP_HOST: 'http://45.77.223.21',
      PLAYGROUND_ENV: 'simulator',
      OPEN_STRATEGY: 'simple_open_strategy_v1',
      START_DATE: '2025-01-19',
      STOP_DATE: '2025-01-24',
      MODEL_UPDATE_FREQUENCY: 'monthly',
      N_CALLS: '30',
    },
    interpreter: 'src/cmd/stats/env/bin/python',
  },{
    name: 'optimizer-coin',
    cmd: 'src/cmd/stats/trading_engine_optimizer.py',
    args: '',
    autorestart: false,
    watch: false,
    instances: 1,
    max_memory_restart: '1G',
    env: {
      BALANCE: '10000',
      SYMBOL: 'COIN',
      TWIRP_HOST: 'http://45.77.223.21',
      PLAYGROUND_ENV: 'simulator',
      OPEN_STRATEGY: 'simple_open_strategy_v1',
      START_DATE: '2025-01-19',
      STOP_DATE: '2025-01-24',
      MODEL_UPDATE_FREQUENCY: 'monthly',
      N_CALLS: '30',
    },
    interpreter: 'src/cmd/stats/env/bin/python',
  },{
    name: 'optimizer-tsla',
    cmd: 'src/cmd/stats/trading_engine_optimizer.py',
    args: '',
    autorestart: false,
    watch: false,
    instances: 1,
    max_memory_restart: '1G',
    env: {
      BALANCE: '10000',
      SYMBOL: 'TSLA',
      TWIRP_HOST: 'http://45.77.223.21',
      PLAYGROUND_ENV: 'simulator',
      OPEN_STRATEGY: 'simple_open_strategy_v1',
      START_DATE: '2025-01-19',
      STOP_DATE: '2025-01-24',
      MODEL_UPDATE_FREQUENCY: 'monthly',
      N_CALLS: '30',
    },
    interpreter: 'src/cmd/stats/env/bin/python',
  },{
    name: 'optimizer-meta',
    cmd: 'src/cmd/stats/trading_engine_optimizer.py',
    args: '',
    autorestart: false,
    watch: false,
    instances: 1,
    max_memory_restart: '1G',
    env: {
      BALANCE: '10000',
      SYMBOL: 'META',
      TWIRP_HOST: 'http://45.77.223.21',
      PLAYGROUND_ENV: 'simulator',
      OPEN_STRATEGY: 'simple_open_strategy_v1',
      START_DATE: '2025-01-19',
      STOP_DATE: '2025-01-24',
      MODEL_UPDATE_FREQUENCY: 'monthly',
      N_CALLS: '30',
    },
    interpreter: 'src/cmd/stats/env/bin/python',
  },{
    name: 'optimizer-nvda',
    cmd: 'src/cmd/stats/trading_engine_optimizer.py',
    args: '',
    autorestart: false,
    watch: false,
    instances: 1,
    max_memory_restart: '1G',
    env: {
      BALANCE: '10000',
      SYMBOL: 'NVDA',
      TWIRP_HOST: 'http://45.77.223.21',
      PLAYGROUND_ENV: 'simulator',
      OPEN_STRATEGY: 'simple_open_strategy_v1',
      START_DATE: '2025-01-19',
      STOP_DATE: '2025-01-24',
      MODEL_UPDATE_FREQUENCY: 'monthly',
      N_CALLS: '30',
    },
    interpreter: 'src/cmd/stats/env/bin/python',
  }]
};