version: '3'

tasks:
  cleanup:vultr:
    cmds:
      - './cleanup_docker_images_remote.sh'
    dir: ${PROJECTS_DIR}/slack-trading

  cleanup:docker:
    cmds:
      - './cleanup_old_docker_images.sh'
      - 'docker volume prune -f'
    dir: ${PROJECTS_DIR}/slack-trading

  conda:list:
    cmds:
      - 'conda env list'

  conda:update:grodt:
    cmds:
      - 'conda update conda'
      - 'conda update --all'
      - 'conda env export > conda-env.yaml'
    dir: ${PROJECTS_DIR}/slack-trading

  conda:update:trading:
    cmds:
      - 'conda update conda'
      - 'conda update --all'
      - 'conda env export > conda-env-trading.yaml'
    dir: ${PROJECTS_DIR}/slack-trading

  list:
    cmds:
      - 'task --list-all'

  rc:
    cmds:
      - 'mosh root@149.28.225.5'

  python:install:
    cmds:
      - 'rm -rf env'
      - 'python3.10 -m venv env'
      - 'task python:upgrade'
    dir: ${PROJECTS_DIR}/slack-trading/src/cmd/stats

  python:upgrade:
    cmds:
      - 'pip install --upgrade pip'
      - 'pip install -r requirements.txt'
    dir: ${PROJECTS_DIR}/slack-trading/src/cmd/stats

  optimize:monthly:
    cmds:
      - 'env/bin/python trading_engine_optimizer.py'
    dir: ${PROJECTS_DIR}/slack-trading/src/cmd/stats
    env:
      BALANCE: "10000"
      SYMBOL: "{{.symbol}}"
      TWIRP_HOST: "http://45.77.223.21"
      PLAYGROUND_ENV: "simulator"
      OPEN_STRATEGY: "simple_open_strategy_v1"
      START_DATE: "2024-12-15"
      STOP_DATE: "2025-01-24"
      MODEL_UPDATE_FREQUENCY: "monthly"
    var:
      symbol: ""

  optimize:weekly:
    cmds:
      - 'env/bin/python trading_engine_optimizer.py'
    dir: ${PROJECTS_DIR}/slack-trading/src/cmd/stats
    env:
      BALANCE: "10000"
      SYMBOL: "{{.symbol}}"
      TWIRP_HOST: "http://45.77.223.21"
      PLAYGROUND_ENV: "simulator"
      OPEN_STRATEGY: "simple_open_strategy_v1"
      START_DATE: "2024-12-15"
      STOP_DATE: "2025-01-24"
      MODEL_UPDATE_FREQUENCY: "weekly"
    var:
      symbol: ""

  run:optimizer:
    cmds:
      - task optimize:weekly -v symbol=COIN
      - task optimize:weekly -v symbol=TSLA
      - task optimize:weekly -v symbol=META
      - task optimize:weekly -v symbol=NVDA
      - task optimize:weekly -v symbol=AAPL
    parallel: true

  optimize:daily:
    cmds:
      - 'env/bin/python trading_engine_optimizer.py'
    dir: ${PROJECTS_DIR}/slack-trading/src/cmd/stats
    env:
      BALANCE: "10000"
      SYMBOL: "{{.symbol}}"
      TWIRP_HOST: "http://45.77.223.21"
      PLAYGROUND_ENV: "simulator"
      OPEN_STRATEGY: "simple_open_strategy_v1"
      START_DATE: "2024-12-15"
      STOP_DATE: "2025-01-24"
      MODEL_UPDATE_FREQUENCY: "daily"
    var:
      symbol: ""

  test:
    cmds:
      - 'go test -count=1 ./...'
    dir: ${PROJECTS_DIR}/slack-trading/src/backtester-api

  test:e2e:live-account-close-with-id:
    cmds:
      - 'go test -timeout 60s -count=1 -run ^TestLiveAccountCloseWithID$ github.com/jiaming2012/slack-trading/integration_testing'
    dir: ${PROJECTS_DIR}/slack-trading/integration_testing

  test:e2e:live-account-filled:
    cmds:
      - 'go test -timeout 60s -count=1 -run ^TestLiveAccountFilled$ github.com/jiaming2012/slack-trading/integration_testing'
    dir: ${PROJECTS_DIR}/slack-trading/integration_testing

  test:e2e:live-account-close:
    cmds:
      - 'go test -timeout 90s -count=1 -run ^TestLiveAccountClose$ github.com/jiaming2012/slack-trading/integration_testing'
    dir: ${PROJECTS_DIR}/slack-trading/integration_testing
  
  test:e2e:live-account-multiple-playgrounds:
    cmds:
      - 'go test -timeout 60s -count=1 -run ^TestLiveAccountMultiplePlaygrounds$ github.com/jiaming2012/slack-trading/integration_testing'
    dir: ${PROJECTS_DIR}/slack-trading/integration_testing

  test:e2e:live-account-duplicate-orders:
    cmds:
      - 'go test -timeout 60s -count=1 -run ^TestLiveAccountDuplicateOrdersTest$ github.com/jiaming2012/slack-trading/integration_testing'
    dir: ${PROJECTS_DIR}/slack-trading/integration_testing

  test:e2e:live-account-close-duplicate-rejected:
    cmds:
      - 'go test -timeout 120s -count=1 -run ^TestLiveAccountCloseDuplicateRejected$ github.com/jiaming2012/slack-trading/integration_testing'
    dir: ${PROJECTS_DIR}/slack-trading/integration_testing

  test:e2e:live-account-close-duplicate-canceled:
    cmds:
      - 'go test -timeout 120s -count=1 -run ^TestLiveAccountCloseDuplicateCanceled$ github.com/jiaming2012/slack-trading/integration_testing'
    dir: ${PROJECTS_DIR}/slack-trading/integration_testing

  test:e2e:live-account-multiple-open:
    cmds:
      - 'go test -timeout 120s -count=1 -run ^TestLiveAccountMultipleOpen$ github.com/jiaming2012/slack-trading/integration_testing'
    dir: ${PROJECTS_DIR}/slack-trading/integration_testing 

  test:e2e:live-account-reject-order:
    cmds:
      - 'go test -timeout 60s -count=1 -run ^TestLiveAccountRejectOrder$ github.com/jiaming2012/slack-trading/integration_testing'
    dir: ${PROJECTS_DIR}/slack-trading/integration_testing 

  test:e2e:live-account-cancel-order:
    cmds:
      - 'go test -timeout 60s -count=1 -run ^TestLiveAccountCancelOrder$ github.com/jiaming2012/slack-trading/integration_testing'
    dir: ${PROJECTS_DIR}/slack-trading/integration_testing 

  test:e2e:all:
    cmds:
      - task test:e2e:live-account-filled
      - task test:e2e:live-account-close
      - task test:e2e:live-account-multiple-playgrounds
      - task test:e2e:live-account-duplicate-orders
      - task test:e2e:live-account-close-with-id
      - task test:e2e:live-account-close-duplicate-rejected
      - task test:e2e:live-account-close-duplicate-canceled
      - task test:e2e:live-account-multiple-open
      - task test:e2e:live-account-reject-order
      - task test:e2e:live-account-cancel-order
    dir: ${PROJECTS_DIR}/slack-trading/integration_testing

  metrics:token:
    cmds:
      - 'kubectl -n kubernetes-dashboard create token --duration=24h dashboard-admin'

  test:integration:
    cmds:
      # - 'go run main.go'
      - 'go test ./...'
    dir: ${PROJECTS_DIR}/slack-trading/src/eventservices/integration_tests

  commit:
    cmds:
      - 'task test'
      - 'git add .'
      - 'git commit -m "{{.CLI_ARGS}}"'
      - 'git push'
      
  app:dev:
    cmds:
      - './run-dev.sh'
    dir: ${PROJECTS_DIR}/slack-trading/src/eventmain

  app:build:
    cmds:
      - 'docker build -t ewr.vultrcr.com/grodt/app:latest -f Dockerfile .'
    dir: ${PROJECTS_DIR}/slack-trading

  app:logs:
    cmds:
      - 'stern grodt --container-state running'

  app:restart:
    cmds:
      - 'task app:stop'
      - 'task app:start'

  app:stop:
    cmds:
      - 'kubectl scale deployment grodt --replicas=0'

  app:update:
    cmds:
      - 'kubectl rollout restart deployment grodt'

  app:start:
    cmds:
      - 'kubectl scale deployment grodt --replicas=1'

  app:build-dev:
    cmds:
      - 'docker build -t ewr.vultrcr.com/grodt/app:latest-dev -f Dockerfile .'
    dir: ${PROJECTS_DIR}/slack-trading
      
  app:deploy:
    cmds:
      - './deploy-app.sh {{.version}}'
    dir: ${PROJECTS_DIR}/slack-trading
    var:
      version: ""
      
  metrics:
    cmds:
      - './env/bin/python playground_metrics.py --playground-id {{.playgroundId}}'
    dir: ${PROJECTS_DIR}/slack-trading/src/cmd/stats
    var:
      playgroundId: ""

  esdb:pf:
    cmds:
      - 'kubectl port-forward svc/eventstoredb 2113:2113 -n eventstoredb'

  pg:pf:
    cmds:
      - 'kubectl port-forward svc/postgres 5432:5432 -n database'

  db:start:
    cmds:
      - 'docker-compose -f ${PROJECTS_DIR}/slack-trading/eventstoredb/docker-compose.yaml up'

  gen:proto:
    cmds:
      - 'source ${PROJECTS_DIR}/slack-trading/src/cmd/stats/env/bin/activate'
      - 'protoc --proto_path=${PROJECTS_DIR}/slack-trading/src --go_out=${PROJECTS_DIR}/slack-trading --python_out=${PROJECTS_DIR}/slack-trading/src/cmd/stats --twirp_out=${PROJECTS_DIR}/slack-trading --twirpy_out=${PROJECTS_DIR}/slack-trading/src/cmd/stats ${PROJECTS_DIR}/slack-trading/src/playground.proto'
      - 'mv ${PROJECTS_DIR}/slack-trading/playground/playground.pb.go ${PROJECTS_DIR}/slack-trading/src/playground'
      - 'mv ${PROJECTS_DIR}/slack-trading/playground/playground.twirp.go ${PROJECTS_DIR}/slack-trading/src/playground'
      - 'rm -rf ${PROJECTS_DIR}/playground'
      - 'mv ${PROJECTS_DIR}/slack-trading/src/cmd/stats/playground_pb2.py ${PROJECTS_DIR}/slack-trading/src/cmd/stats/rpc'
      - 'mv ${PROJECTS_DIR}/slack-trading/src/cmd/stats/playground_twirp.py ${PROJECTS_DIR}/slack-trading/src/cmd/stats/rpc'
      - 'rm -rf ${PROJECTS_DIR}/slack-trading/src/cmd/stats/playground_pb2.py'
      - 'rm -rf ${PROJECTS_DIR}/slack-trading/src/cmd/stats/playground_twirp.py'
