version: '3'

tasks:
  list:
    cmds:
      - 'task --list-all'

  rc:
    cmds:
      - 'mosh root@149.28.225.5'

  python:install:
    cmds:
      - 'rm -rf env'
      - 'python3.10 -m venv env'
      - 'task python:upgrade'
    dir: ${PROJECTS_DIR}/slack-trading/src/cmd/stats

  python:upgrade:
    cmds:
      - 'pip install --upgrade pip'
      - 'pip install -r requirements.txt'
    dir: ${PROJECTS_DIR}/slack-trading/src/cmd/stats

  optimize:monthly:
    cmds:
      - 'env/bin/python trading_engine_optimizer.py'
    dir: ${PROJECTS_DIR}/slack-trading/src/cmd/stats
    env:
      BALANCE: "10000"
      SYMBOL: "{{.symbol}}"
      GRPC_HOST: "http://45.77.223.21"
      PLAYGROUND_ENV: "simulator"
      OPEN_STRATEGY: "simple_open_strategy_v1"
      START_DATE: "2024-12-15"
      STOP_DATE: "2025-01-24"
      MODEL_UPDATE_FREQUENCY: "monthly"
    var:
      symbol: ""

  optimize:weekly:
    cmds:
      - 'env/bin/python trading_engine_optimizer.py'
    dir: ${PROJECTS_DIR}/slack-trading/src/cmd/stats
    env:
      BALANCE: "10000"
      SYMBOL: "{{.symbol}}"
      GRPC_HOST: "http://45.77.223.21"
      PLAYGROUND_ENV: "simulator"
      OPEN_STRATEGY: "simple_open_strategy_v1"
      START_DATE: "2024-12-15"
      STOP_DATE: "2025-01-24"
      MODEL_UPDATE_FREQUENCY: "weekly"
    var:
      symbol: ""

  run:optimizer:
    cmds:
      - task optimize:weekly -v symbol=COIN
      - task optimize:weekly -v symbol=TSLA
      - task optimize:weekly -v symbol=META
      - task optimize:weekly -v symbol=NVDA
      - task optimize:weekly -v symbol=AAPL
    parallel: true

  optimize:daily:
    cmds:
      - 'env/bin/python trading_engine_optimizer.py'
    dir: ${PROJECTS_DIR}/slack-trading/src/cmd/stats
    env:
      BALANCE: "10000"
      SYMBOL: "{{.symbol}}"
      GRPC_HOST: "http://45.77.223.21"
      PLAYGROUND_ENV: "simulator"
      OPEN_STRATEGY: "simple_open_strategy_v1"
      START_DATE: "2024-12-15"
      STOP_DATE: "2025-01-24"
      MODEL_UPDATE_FREQUENCY: "daily"
    var:
      symbol: ""

  test:
    cmds:
      - 'go test ./...'
    dir: ${PROJECTS_DIR}/slack-trading/src/backtester-api

  test:integration:
    cmds:
      - 'go test ./...'
    dir: ${PROJECTS_DIR}/slack-trading/integration_testing
  
  metrics:token:
    cmds:
      - 'kubectl -n kubernetes-dashboard create token --duration=24h dashboard-admin'

  test:integration:
    cmds:
      # - 'go run main.go'
      - 'go test ./...'
    dir: ${PROJECTS_DIR}/slack-trading/src/eventservices/integration_tests

  commit:
    cmds:
      - 'task test'
      - 'git commit'

  run:dev:
    cmds:
      - './run-dev.sh'
    dir: ${PROJECTS_DIR}/slack-trading/src/eventmain

  build:app:
    cmds:
      - 'docker build -t ewr.vultrcr.com/grodt/app:latest -f Dockerfile .'
    dir: ${PROJECTS_DIR}/slack-trading

  metrics:
    cmds:
      - './env/bin/python playground_metrics.py --playground-id {{.playgroundId}}'
    dir: ${PROJECTS_DIR}/slack-trading/src/cmd/stats
    var:
      playgroundId: ""

  deploy:app:
    cmds:
      - './deploy-app.sh {{.version}}'
    dir: ${PROJECTS_DIR}/slack-trading
    var:
      version: ""

  esdb:connect:
    cmds:
      - 'kubectl port-forward svc/eventstoredb 2113:2113 -n eventstoredb'

  pg:connect:
    cmds:
      - 'kubectl port-forward svc/postgres 5432:5432 -n database'

  db:start:
    cmds:
      - 'docker-compose -f ${PROJECTS_DIR}/slack-trading/eventstoredb/docker-compose.yaml up'

  gen:proto:
    cmds:
      - 'source ${PROJECTS_DIR}/slack-trading/src/cmd/stats/env/bin/activate'
      - 'protoc --proto_path=${PROJECTS_DIR}/slack-trading/src --go_out=${PROJECTS_DIR}/slack-trading --python_out=${PROJECTS_DIR}/slack-trading/src/cmd/stats --twirp_out=${PROJECTS_DIR}/slack-trading --twirpy_out=${PROJECTS_DIR}/slack-trading/src/cmd/stats ${PROJECTS_DIR}/slack-trading/src/playground.proto'
      - 'mv ${PROJECTS_DIR}/slack-trading/playground/playground.pb.go ${PROJECTS_DIR}/slack-trading/src/playground'
      - 'mv ${PROJECTS_DIR}/slack-trading/playground/playground.twirp.go ${PROJECTS_DIR}/slack-trading/src/playground'
      - 'rm -rf ${PROJECTS_DIR}/playground'
      - 'mv ${PROJECTS_DIR}/slack-trading/src/cmd/stats/playground_pb2.py ${PROJECTS_DIR}/slack-trading/src/cmd/stats/rpc'
      - 'mv ${PROJECTS_DIR}/slack-trading/src/cmd/stats/playground_twirp.py ${PROJECTS_DIR}/slack-trading/src/cmd/stats/rpc'
      - 'rm -rf ${PROJECTS_DIR}/slack-trading/src/cmd/stats/playground_pb2.py'
      - 'rm -rf ${PROJECTS_DIR}/slack-trading/src/cmd/stats/playground_twirp.py'
