module.exports = {
  apps : [{
    name: 'supertrend1-coin-simulation-basic',
    cmd: 'src/cmd/stats/trading_engine.py',
    args: '--sl-shift 0.0 --tp-shift 0.0 --sl-buffer 1.0 --tp-buffer 1.0 --min-max-window-in-hours 11',
    autorestart: false,
    watch: false,
    instances: 1,
    max_memory_restart: '1G',
    env: {
      BALANCE: '3000',
      SYMBOL: 'COIN',
      GRPC_HOST: 'http://localhost:5051',
      OPEN_STRATEGY: 'simple_open_strategy_v1',
      MODEL_UPDATE_FREQUENCY: 'daily',
      OPTIMIZER_UPDATE_FREQUENCY: 'weekly',
      PLAYGROUND_ENV: 'simulator',
      START_DATE: '2024-11-01',
      STOP_DATE: '2025-01-31',
      N_CALLS: '40',
    },
    env_prod: {
      GRPC_HOST: 'http://45.77.223.21',
    },
    interpreter: 'src/cmd/stats/env/bin/python',
  },{
    name: 'supertrend1-coin-simulation-v2',
    cmd: 'src/cmd/stats/trading_engine.py',
    args: '',
    autorestart: false,
    watch: false,
    instances: 1,
    max_memory_restart: '1G',
    env: {
      BALANCE: '3000',
      SYMBOL: 'COIN',
      GRPC_HOST: 'http://localhost:5051',
      OPEN_STRATEGY: 'simple_open_strategy_v2',
      MODEL_UPDATE_FREQUENCY: 'daily',
      OPTIMIZER_UPDATE_FREQUENCY: 'weekly',
      PLAYGROUND_ENV: 'simulator',
      START_DATE: '2024-11-01',
      STOP_DATE: '2025-01-31',
      N_CALLS: '40',
    },
    env_prod: {
      GRPC_HOST: 'http://45.77.223.21',
    },
    interpreter: 'src/cmd/stats/env/bin/python',
  },{
    name: 'supertrend1-nvda-simulation-basic',
    cmd: 'src/cmd/stats/trading_engine.py',
    args: '--sl-shift 0.0 --tp-shift 0.0 --sl-buffer 1.0 --tp-buffer 1.0 --min-max-window-in-hours 11',
    autorestart: false,
    watch: false,
    instances: 1,
    max_memory_restart: '1G',
    env: {
      BALANCE: '3000',
      SYMBOL: 'NVDA',
      GRPC_HOST: 'http://localhost:5051',
      OPEN_STRATEGY: 'simple_open_strategy_v1',
      MODEL_UPDATE_FREQUENCY: 'daily',
      OPTIMIZER_UPDATE_FREQUENCY: 'weekly',
      PLAYGROUND_ENV: 'simulator',
      START_DATE: '2024-11-01',
      STOP_DATE: '2025-01-31',
      N_CALLS: '40',
    },
    env_prod: {
      GRPC_HOST: 'http://45.77.223.21',
    },
    interpreter: 'src/cmd/stats/env/bin/python',
  },{
    name: 'supertrend1-nvda-simulation-v2',
    cmd: 'src/cmd/stats/trading_engine.py',
    args: '',
    autorestart: false,
    watch: false,
    instances: 1,
    max_memory_restart: '1G',
    env: {
      BALANCE: '3000',
      SYMBOL: 'NVDA',
      GRPC_HOST: 'http://localhost:5051',
      OPEN_STRATEGY: 'simple_open_strategy_v2',
      MODEL_UPDATE_FREQUENCY: 'daily',
      OPTIMIZER_UPDATE_FREQUENCY: 'weekly',
      PLAYGROUND_ENV: 'simulator',
      START_DATE: '2024-11-01',
      STOP_DATE: '2025-01-31',
      N_CALLS: '40',
    },
    env_prod: {
      GRPC_HOST: 'http://45.77.223.21',
    },
    interpreter: 'src/cmd/stats/env/bin/python',
  },{
    name: 'supertrend1-meta-simulation-v2',
    cmd: 'src/cmd/stats/trading_engine.py',
    args: '',
    autorestart: false,
    watch: false,
    instances: 1,
    max_memory_restart: '1G',
    env: {
      BALANCE: '3000',
      SYMBOL: 'META',
      GRPC_HOST: 'http://localhost:5051',
      OPEN_STRATEGY: 'simple_open_strategy_v2',
      MODEL_UPDATE_FREQUENCY: 'daily',
      OPTIMIZER_UPDATE_FREQUENCY: 'weekly',
      PLAYGROUND_ENV: 'simulator',
      START_DATE: '2024-11-01',
      STOP_DATE: '2025-01-31',
      N_CALLS: '40',
    },
    env_prod: {
      GRPC_HOST: 'http://45.77.223.21',
    },
    interpreter: 'src/cmd/stats/env/bin/python',
  },{
    name: 'supertrend1-tsla-simulation-v2',
    cmd: 'src/cmd/stats/trading_engine.py',
    args: '',
    autorestart: false,
    watch: false,
    instances: 1,
    max_memory_restart: '1G',
    env: {
      BALANCE: '3000',
      SYMBOL: 'TSLA',
      GRPC_HOST: 'http://localhost:5051',
      OPEN_STRATEGY: 'simple_open_strategy_v2',
      MODEL_UPDATE_FREQUENCY: 'daily',
      OPTIMIZER_UPDATE_FREQUENCY: 'weekly',
      PLAYGROUND_ENV: 'simulator',
      START_DATE: '2024-11-01',
      STOP_DATE: '2025-01-31',
      N_CALLS: '40',
    },
    env_prod: {
      GRPC_HOST: 'http://45.77.223.21',
    },
    interpreter: 'src/cmd/stats/env/bin/python',
  },{
    name: 'supertrend1-aapl-simulation-v2',
    cmd: 'src/cmd/stats/trading_engine.py',
    args: '',
    autorestart: false,
    watch: false,
    instances: 1,
    max_memory_restart: '1G',
    env: {
      BALANCE: '3000',
      SYMBOL: 'AAPL',
      GRPC_HOST: 'http://localhost:5051',
      OPEN_STRATEGY: 'simple_open_strategy_v2',
      MODEL_UPDATE_FREQUENCY: 'daily',
      OPTIMIZER_UPDATE_FREQUENCY: 'weekly',
      PLAYGROUND_ENV: 'simulator',
      START_DATE: '2024-11-01',
      STOP_DATE: '2025-01-31',
      N_CALLS: '40',
    },
    env_prod: {
      GRPC_HOST: 'http://45.77.223.21',
    },
    interpreter: 'src/cmd/stats/env/bin/python',
  }, {
  name: 'supertrend1-coin-simulation-basic-weekly',
    cmd: 'src/cmd/stats/trading_engine.py',
    args: '--sl-shift 0.0 --tp-shift 0.0 --sl-buffer 1.0 --tp-buffer 1.0 --min-max-window-in-hours 11',
    autorestart: false,
    watch: false,
    instances: 1,
    max_memory_restart: '1G',
    env: {
      BALANCE: '3000',
      SYMBOL: 'COIN',
      GRPC_HOST: 'http://localhost:5051',
      OPEN_STRATEGY: 'simple_open_strategy_v1',
      MODEL_UPDATE_FREQUENCY: 'weekly',
      OPTIMIZER_UPDATE_FREQUENCY: 'weekly',
      PLAYGROUND_ENV: 'simulator',
      START_DATE: '2024-11-01',
      STOP_DATE: '2025-01-31',
      N_CALLS: '40',
    },
    env_prod: {
      GRPC_HOST: 'http://45.77.223.21',
    },
    interpreter: 'src/cmd/stats/env/bin/python',
  }, {
    name: 'supertrend1-nvda-simulation-basic-weekly',
      cmd: 'src/cmd/stats/trading_engine.py',
      args: '--sl-shift 0.0 --tp-shift 0.0 --sl-buffer 1.0 --tp-buffer 1.0 --min-max-window-in-hours 11',
      autorestart: false,
      watch: false,
      instances: 1,
      max_memory_restart: '1G',
      env: {
        BALANCE: '3000',
        SYMBOL: 'NVDA',
        GRPC_HOST: 'http://localhost:5051',
        OPEN_STRATEGY: 'simple_open_strategy_v1',
        MODEL_UPDATE_FREQUENCY: 'weekly',
        OPTIMIZER_UPDATE_FREQUENCY: 'weekly',
        PLAYGROUND_ENV: 'simulator',
        START_DATE: '2024-11-01',
        STOP_DATE: '2025-01-31',
        N_CALLS: '40',
      },
      env_prod: {
        GRPC_HOST: 'http://45.77.223.21',
      },
      interpreter: 'src/cmd/stats/env/bin/python',
    }]
};