module.exports = {
  apps : [{
    name: 'supertrend1-aapl',
    cmd: 'src/cmd/stats/trading_engine.py',
    args: '--sl-shift 0 --tp-shift 0 --sl-buffer 1.0 --tp-buffer 1.0 --min-max-window-in-hours 11',
    autorestart: true,
    watch: false,
    instances: 1,
    max_memory_restart: '1G',
    env: {
      BALANCE: '3000',
      SYMBOL: 'AAPL',
      // GRPC_HOST: 'http://45.77.223.21',
      GRPC_HOST: 'http://localhost:5051',
      OPEN_STRATEGY: 'simple_open_strategy_v1',
      MODEL_UPDATE_FREQUENCY: 'daily',
      OPTIMIZER_UPDATE_FREQUENCY: 'weekly',
      N_CALLS: '30',
    },
    env_simulation: {
      PLAYGROUND_ENV: 'simulator',
      START_DATE: '2024-11-01',
      STOP_DATE: '2025-01-31',
    },
    env_paper: {
      PLAYGROUND_ENV: 'live',
      LIVE_ACCOUNT_TYPE: 'paper',
    },
    env_production : {
      PLAYGROUND_CLIENT_ID: 'supertrend1-aapl-margin',
      PLAYGROUND_ENV: 'live',
      LIVE_ACCOUNT_TYPE: 'margin',
    },
    interpreter: '${ANACONDA_HOME}/envs/trading/bin/python',
  },{
    name: 'supertrend1-coin',
    cmd: 'src/cmd/stats/trading_engine.py',
    args: '--sl-shift 0 --tp-shift 0 --sl-buffer 1.0 --tp-buffer 1.0 --min-max-window-in-hours 11',
    autorestart: true,
    watch: false,
    instances: 1,
    max_memory_restart: '1G',
    env: {
      BALANCE: '3000',
      SYMBOL: 'COIN',
      // GRPC_HOST: 'http://45.77.223.21',
      GRPC_HOST: 'http://localhost:5051',
      OPEN_STRATEGY: 'simple_open_strategy_v1',
      MODEL_UPDATE_FREQUENCY: 'daily',
      OPTIMIZER_UPDATE_FREQUENCY: 'weekly',
      N_CALLS: '30',
    },
    env_paper: {
      PLAYGROUND_ENV: 'live',
      LIVE_ACCOUNT_TYPE: 'paper',
    },
    env_production : {
      PLAYGROUND_CLIENT_ID: 'supertrend1-coin-margin',
      PLAYGROUND_ENV: 'live',
      LIVE_ACCOUNT_TYPE: 'margin',
    },
    interpreter: '${ANACONDA_HOME}/envs/trading/bin/python',
  },{
    name: 'supertrend1-meta',
    cmd: 'src/cmd/stats/trading_engine.py',
    args: '--sl-shift 0 --tp-shift 0 --sl-buffer 1.0 --tp-buffer 1.0 --min-max-window-in-hours 11',
    autorestart: true,
    watch: false,
    instances: 1,
    max_memory_restart: '1G',
    env: {
      BALANCE: '3000',
      SYMBOL: 'META',
      // GRPC_HOST: 'http://45.77.223.21',
      GRPC_HOST: 'http://localhost:5051',
      OPEN_STRATEGY: 'simple_open_strategy_v1',
      MODEL_UPDATE_FREQUENCY: 'daily',
      OPTIMIZER_UPDATE_FREQUENCY: 'weekly',
      N_CALLS: '30',
    },
    env_simulation: {
      PLAYGROUND_ENV: 'simulator',
      START_DATE: '2024-11-01',
      STOP_DATE: '2025-01-31',
    },
    env_paper: {
      PLAYGROUND_ENV: 'live',
      LIVE_ACCOUNT_TYPE: 'paper',
    },
    env_production : {
      PLAYGROUND_CLIENT_ID: 'supertrend1-meta-margin',
      PLAYGROUND_ENV: 'live',
      LIVE_ACCOUNT_TYPE: 'margin',
    },
    interpreter: '${ANACONDA_HOME}/envs/trading/bin/python',
  },{
    name: 'supertrend1-nvda',
    cmd: 'src/cmd/stats/trading_engine.py',
    args: '--sl-shift 0 --tp-shift 0 --sl-buffer 1.0 --tp-buffer 1.0 --min-max-window-in-hours 11',
    autorestart: true,
    watch: false,
    instances: 1,
    max_memory_restart: '1G',
    env: {
      BALANCE: '3000',
      SYMBOL: 'NVDA',
      // GRPC_HOST: 'http://45.77.223.21',
      GRPC_HOST: 'http://localhost:5051',
      OPEN_STRATEGY: 'simple_open_strategy_v1',
      MODEL_UPDATE_FREQUENCY: 'daily',
      OPTIMIZER_UPDATE_FREQUENCY: 'weekly',
      N_CALLS: '30',
    },
    env_simulation: {
      PLAYGROUND_ENV: 'simulator',
      START_DATE: '2024-11-01',
      STOP_DATE: '2025-01-31',
    },
    env_paper: {
      PLAYGROUND_ENV: 'live',
      LIVE_ACCOUNT_TYPE: 'paper',
    },
    env_production : {
      PLAYGROUND_CLIENT_ID: 'supertrend1-nvda-margin-2',
      PLAYGROUND_ENV: 'live',
      LIVE_ACCOUNT_TYPE: 'margin',
    },
    interpreter: '${ANACONDA_HOME}/envs/trading/bin/python',
  },{
    name: 'supertrend1-tsla',
    cmd: 'src/cmd/stats/trading_engine.py',
    args: '--sl-shift 0 --tp-shift 0 --sl-buffer 1.0 --tp-buffer 1.0 --min-max-window-in-hours 11',
    autorestart: true,
    watch: false,
    instances: 1,
    max_memory_restart: '1G',
    env: {
      BALANCE: '3000',
      SYMBOL: 'TSLA',
      // GRPC_HOST: 'http://45.77.223.21',
      GRPC_HOST: 'http://localhost:5051',
      OPEN_STRATEGY: 'simple_open_strategy_v1',
      MODEL_UPDATE_FREQUENCY: 'daily',
      OPTIMIZER_UPDATE_FREQUENCY: 'weekly',
      N_CALLS: '30',
    },
    env_simulation: {
      PLAYGROUND_ENV: 'simulator',
      START_DATE: '2024-11-01',
      STOP_DATE: '2025-01-31',
    },
    env_paper: {
      PLAYGROUND_ENV: 'live',
      LIVE_ACCOUNT_TYPE: 'paper',
    },
    env_production : {
      PLAYGROUND_CLIENT_ID: 'supertrend1-tsla-margin',
      PLAYGROUND_ENV: 'live',
      LIVE_ACCOUNT_TYPE: 'margin',
    },
    interpreter: '${ANACONDA_HOME}/envs/trading/bin/python',
  }]
};