apiVersion: v1
kind: ConfigMap
metadata:
  name: grodt-configmap
  namespace: default
data:
  PROJECTS_DIR: "/app"
  ENV: "production"
  GO_ENV: "production"
  ANACONDA_HOME: "/opt/conda"
  TRADIER_STOCK_QUOTES_URL: "https://api.tradier.com/v1/markets/quotes"
  TRADIER_MARKET_CALENDAR_URL: "https://api.tradier.com/v1/markets/calendar"
  TRADIER_OPTION_CHAIN_URL: "https://api.tradier.com/v1/markets/options/chains"
  TRADIER_OPTION_EXPIRATIONS_URL: "https://api.tradier.com/v1/markets/options/expirations"
  TRAIER_QUOTES_HISTORY_URL: "https://api.tradier.com/v1/markets/history"
  TRADIER_MARKET_TIMESALES_URL: "https://api.tradier.com/v1/markets/timesales"
  TRADIER_LIVE_ACCOUNT_ID: "6YA49543"
  TRADIER_LIVE_TRADES_ACCOUNT_ID: "6YA49543"
  TRADIER_LIVE_TRADES_URL_TEMPLATE: "https://api.tradier.com/v1/accounts/%s/orders"
  TRADIER_LIVE_POSITIONS_URL_TEMPLATE: "https://api.tradier.com/v1/accounts/%s/positions"
  TRADIER_LIVE_BALANCES_URL_TEMPLATE: "https://api.tradier.com/v1/accounts/%s/balances"
  TRADIER_SANDBOX_ACCOUNT_ID: "6YA49543"
  TRADIER_SANDBOX_TRADES_ACCOUNT_ID: "VA12962195"
  TRADIER_SANDBOX_TRADES_URL_TEMPLATE: "https://sandbox.tradier.com/v1/accounts/%s/orders"
  TRADIER_SANDBOX_POSITIONS_URL_TEMPLATE: "https://sandbox.tradier.com/v1/accounts/%s/positions"
  TRADIER_SANDBOX_BALANCES_URL_TEMPLATE: "https://sandbox.tradier.com/v1/accounts/%s/balances"
  EVENTSTOREDB_URL: "esdb://admin:changeit@eventstoredb.eventstoredb.svc.cluster.local:2113?tls=false&keepAliveTimeout=10000&keepAliveInterval=10000"
  OANDA_FX_QUOTES_URL_BASE: "https://api-fxtrade.oanda.com/v3/instruments/%s/candles"
  LOG_LEVEL: "trace"
  DRY_RUN: "false"
  OPTIONS_CONFIG_FILE: "options-config-prod.yaml"
  PORT: "8080"
