apiVersion: apps/v1
kind: Deployment
metadata:
  name: grodt
  namespace: default
  labels:
    app: grodt
spec:
  replicas: 0
  selector:
    matchLabels:
      app: grodt
  template:
    metadata:
      labels:
        app: grodt
    spec:
      containers:
      - name: grodt
        image: ewr.vultrcr.com/grodt/app:3.12.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: grodt-configmap
        - secretRef:
            name: grodt-secrets
        - configMapRef:
            name: postgres-configmap
        - secretRef:
            name: postgres-secrets
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
