apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eventstoredb-data
  namespace: eventstoredb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: vultr-block-storage