apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 30s
  url: ssh://git@github.com/jiaming2012/slack-trading
  ref:
    branch: main
  secretRef:
    name: flux-git-deploy
