apiVersion: v1
kind: Service
metadata:
  name: grodt-lb
  namespace: default
  labels:
    app: grodt
spec:
  type: LoadBalancer
  selector:
    app: grodt
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080