apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: database
data:
  POSTGRES_DB: "playground"
  POSTGRES_USER: "grodt"
  POSTGRES_HOST: "postgres.database.svc.cluster.local"