apiVersion: v1
kind: Service
metadata:
  name: grodt
  namespace: default
spec:
  selector:
    app: grodt
  ports:
  - name: twirp
    port: 5051               # The port of the twirp service
    targetPort: 5051         # The port the twirp server is listening on within the pod
    nodePort: 30051           # Port exposed on each node
    protocol: TCP
  - name: http
    port: 8080
    targetPort: 8080          # http port for readiness check
    nodePort: 30080
    protocol: TCP
  type: NodePort