apiVersion: v1
kind: Service
metadata:
  name: grodt
  namespace: default
spec:
  selector:
    app: grodt
  ports:
  - port: 50051              # The port on the service
    targetPort: 50051         # The port the gRPC server is listening on within the pod
    nodePort: 30051           # Port exposed on each node
    protocol: TCP
  type: NodePort