version: "3.4"

services:
  otel-lgtm:
    image: grafana/otel-lgtm
    container_name: otel-lgtm
    ports:
      - "3000:3000"    # Grafana UI
      - "4317:4317"    # OTLP gRPC receiver
      - "4318:4318"    # OTLP HTTP receiver
    environment:
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/otel-lgtm/grafana/conf/provisioning/dashboards/custom/grodt-live-simulation.json
      - SLACK_OPTION_ALERTS_WEBHOOK_URL=${SLACK_OPTION_ALERTS_WEBHOOK_URL}
    volumes:
      - otel-lgtm-data:/data
      # Dashboard provisioning
      - ./dashboards/dashboards-provider.yaml:/otel-lgtm/grafana/conf/provisioning/dashboards/custom.yaml:ro
      - ./dashboards/grodt-live-simulation.json:/otel-lgtm/grafana/conf/provisioning/dashboards/custom/grodt-live-simulation.json:ro
      # Alert provisioning
      - ./alerting/alerting.yaml:/otel-lgtm/grafana/conf/provisioning/alerting/grodt-alerting.yaml:ro

volumes:
  otel-lgtm-data:
