package eventpubsub

type EventName string

const (
	NewTickEvent                EventName = "NewTickEvent"
	NewCandleEvent              EventName = "NewCandleEvent"
	RsiTradeSignal              EventName = "RsiTradeSignal"
	BotTradeRequestEvent        EventName = "BotTradeRequestEvent"
	TradeRequestEvent           EventName = "TradeRequestEvent"
	TradeFulfilledEvent         EventName = "TradeFulfilledEvent"
	VolumeRequestEvent          EventName = "VolumeRequestEvent"
	VolumeResultEvent           EventName = "VolumeResultEvent"
	BalanceRequestEvent         EventName = "BalanceRequestEvent"
	BalanceResultEvent          EventName = "BalanceResultEvent"
	GetAccountsRequestEvent     EventName = "GetAccountsRequestEvent"
	GetAccountsResponseEvent    EventName = "GetAccountsResponseEvent"
	AddAccountRequestEvent      EventName = "AddAccountRequestEvent"
	AddAccountResponseEvent     EventName = "AddAccountResponseEvent"
	SupportBreakSignal          EventName = "SupportBreakSignal"
	ResistanceBreakSignal       EventName = "ResistanceBreakSignal"
	TrendlineBreakSignal        EventName = "TrendlineBreakSignal"
	AddStrategyRequest          EventName = "AddStrategyRequest"
	CloseTradesRequest          EventName = "CloseTradesRequest"
	ExecuteOpenTradeRequest     EventName = "ExecuteOpenTradeRequest"
	ExecuteCloseTradeRequest    EventName = "ExecuteCloseTradeRequest"
	ExecuteCloseTradesRequest   EventName = "ExecuteCloseTradesRequest"
	ExecuteOpenTradeResult      EventName = "ExecuteOpenTradeResult"
	ExecuteCloseTradesResult    EventName = "ExecuteCloseTradesResult"
	NewOpenTradeRequest         EventName = "NewOpenTradeRequest"
	NewGetStatsRequest          EventName = "NewGetStatsRequest"
	GetStatsResult              EventName = "GetStatsResult"
	FetchTradesRequest          EventName = "FetchTradesRequest"
	FetchTradesResult           EventName = "FetchTradesResult"
	NewSignalsRequest           EventName = "NewSignalsRequest"
	NewSignalsResult            EventName = "NewSignalsResult"
	ManualDatafeedUpdateRequest EventName = "ManualDatafeedUpdateRequest"
	ManualDatafeedUpdateResult  EventName = "ManualDatafeedUpdateResult"
	AutoExecuteTrade            EventName = "AutoExecuteTrade"
	Error                       EventName = "DefaultError"
)
