// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: playground.proto

package playground

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlaygroundService_CreatePlayground_FullMethodName = "/playground.PlaygroundService/CreatePlayground"
)

// PlaygroundServiceClient is the client API for PlaygroundService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlaygroundServiceClient interface {
	CreatePlayground(ctx context.Context, in *CreatePolygonPlaygroundRequest, opts ...grpc.CallOption) (*CreatePlaygroundResponse, error)
}

type playgroundServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlaygroundServiceClient(cc grpc.ClientConnInterface) PlaygroundServiceClient {
	return &playgroundServiceClient{cc}
}

func (c *playgroundServiceClient) CreatePlayground(ctx context.Context, in *CreatePolygonPlaygroundRequest, opts ...grpc.CallOption) (*CreatePlaygroundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePlaygroundResponse)
	err := c.cc.Invoke(ctx, PlaygroundService_CreatePlayground_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaygroundServiceServer is the server API for PlaygroundService service.
// All implementations must embed UnimplementedPlaygroundServiceServer
// for forward compatibility.
type PlaygroundServiceServer interface {
	CreatePlayground(context.Context, *CreatePolygonPlaygroundRequest) (*CreatePlaygroundResponse, error)
	mustEmbedUnimplementedPlaygroundServiceServer()
}

// UnimplementedPlaygroundServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlaygroundServiceServer struct{}

func (UnimplementedPlaygroundServiceServer) CreatePlayground(context.Context, *CreatePolygonPlaygroundRequest) (*CreatePlaygroundResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlayground not implemented")
}
func (UnimplementedPlaygroundServiceServer) mustEmbedUnimplementedPlaygroundServiceServer() {}
func (UnimplementedPlaygroundServiceServer) testEmbeddedByValue()                           {}

// UnsafePlaygroundServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlaygroundServiceServer will
// result in compilation errors.
type UnsafePlaygroundServiceServer interface {
	mustEmbedUnimplementedPlaygroundServiceServer()
}

func RegisterPlaygroundServiceServer(s grpc.ServiceRegistrar, srv PlaygroundServiceServer) {
	// If the following call pancis, it indicates UnimplementedPlaygroundServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlaygroundService_ServiceDesc, srv)
}

func _PlaygroundService_CreatePlayground_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePolygonPlaygroundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaygroundServiceServer).CreatePlayground(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaygroundService_CreatePlayground_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaygroundServiceServer).CreatePlayground(ctx, req.(*CreatePolygonPlaygroundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlaygroundService_ServiceDesc is the grpc.ServiceDesc for PlaygroundService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlaygroundService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "playground.PlaygroundService",
	HandlerType: (*PlaygroundServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlayground",
			Handler:    _PlaygroundService_CreatePlayground_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "playground.proto",
}
