options:
  - symbol: SPX
    startsAt: 2022-01-04T09:30:00
    endsAt: 2024-05-31T16:00:00
    expirationsInDays: [7]
    minDistanceBetweenStrikes: 10.0
    maxNoOfStrikes: 4
  - symbol: SPY
    startsAt: 2023-01-04T09:30:00
    endsAt: 2023-12-29T16:00:00
    expirationsInDays: [7]
    minDistanceBetweenStrikes: 10.0
    maxNoOfStrikes: 4
  - symbol: VIX
    startsAt: 2022-01-04T09:30:00
    endsAt: 2024-05-31T16:00:00
    expirationsInDays: [7]
    minDistanceBetweenStrikes: 1.0
    maxNoOfStrikes: 4
  - symbol: IWM
    startsAt: 2022-01-04T09:30:00
    endsAt: 2024-05-31T16:00:00
    expirationsInDays: [7]
    minDistanceBetweenStrikes: 1.0
    maxNoOfStrikes: 4
  - symbol: NDX
    startsAt: 2022-01-04T09:30:00
    endsAt: 2024-05-31T16:00:00
    expirationsInDays: [7]
    minDistanceBetweenStrikes: 10.0
    maxNoOfStrikes: 4
  - symbol: QQQ
    startsAt: 2022-01-04T09:30:00
    endsAt: 2024-05-31T16:00:00
    expirationsInDays: [7]
    minDistanceBetweenStrikes: 1.0
    maxNoOfStrikes: 4
  - symbol: COIN
    startsAt: 2022-01-04T09:30:00
    endsAt: 2024-05-31T16:00:00
    expirationsInDays: [7]
    minDistanceBetweenStrikes: 10.0
    maxNoOfStrikes: 4
  - symbol: CVX
    startsAt: 2022-01-04T09:30:00
    endsAt: 2024-05-31T16:00:00
    expirationsInDays: [7]
    minDistanceBetweenStrikes: 10.0
    maxNoOfStrikes: 4
  - symbol: NVDA
    startsAt: 2022-01-04T09:30:00
    endsAt: 2024-05-31T16:00:00
    expirationsInDays: [7]
    minDistanceBetweenStrikes: 10.0
    maxNoOfStrikes: 4
  - symbol: TSLA
    startsAt: 2022-01-04T09:30:00
    endsAt: 2023-05-31T16:00:00
    expirationsInDays: [7]
    minDistanceBetweenStrikes: 10.0
    maxNoOfStrikes: 4