version: "3.4"

services:
  eventstore.db:
    image: eventstore/eventstore:24.2.0-jammy
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_INT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=playground
      - POSTGRES_USER=grodt
      - POSTGRES_PASSWORD=test747
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgres-volume-data
        target: /var/lib/postgresql/data

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  postgres-volume-data: